from .code_challenge1 import code_C1
from .code_challenge2 import code_C2
from .code_challenge4 import code_C4
from .code_challenge5 import code_C5
from .code_challenge6 import code_C6
from .code_challenge7 import code_C7
from .code_challenge8 import code_C8 
from .code_challenge9 import code_C9
from .code_challenge10 import code_C10
from .code_challenge11 import code_C11
from .code_challenge12 import code_C12
from .code_challenge13 import code_C13
from .code_challenge14 import code_C14
from .code_challenge15 import code_C15
from .code_challenge16 import code_C16
